ENTER_KEY = 10
DELETE_KEY = 127
FINNISH_OPTION = 2

DEFAULT_Y = 3
DEFAULT_X = 5

CREATE_OPTION = 0
RETRIEVE_OPTION = 1
LOGOUT_OPTION = 2

TOP_LEFT_CHAR = "╭"
TOP_RIGHT_CHAR = "╮"
BOTTOM_LEFT_CHAR = "╰"
BOTTOM_RIGHT_CHAR = "╯"
